name: sketch_simplification
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8*
  - torchvision=0.11.2=py39_cu113
  - cudatoolkit=11.3.1
  - pip:
      - tqdm
      - more-itertools